Addeed first implementation of Mobmenu
croixua/command-project-goit pull request #1
Opened 2021-11-13 14:04 UTC by canon318i

Some additional actions are neccesary:
1. Required   <include src="./partials/mobmenu.html"></include> in index.html
2. Required @import './layout/mobmenu'  in main.scss
3. Clear comment in 1-5 lines to show bugger button.
4. Use data-mobilemenu-open for burger button  as shortcut to show menu.

2021-11-13 21:27 UTC, croixua requested changes

2021-11-13 21:27 UTC, croixua commented on src/partials/mobmenu.html
> +    <div class="buy-now">
для чего тут лишний див, если мы можем просто стилизировать кнопку и просто спозиционировать относительно mobile-menu?

и этот код нужно через валидатор прогнать, так как нет закрывающего дива

2021-11-13 21:27 UTC, croixua commented on src/partials/mobmenu.html
> +<script src="./mobile-menu.js"></script>
отдельный паршал я создам, а ты обнови маин и внеси правки

2021-11-13 21:27 UTC, croixua commented on src/partials/mobmenu.html
> +<div class="mobile-menu" data-mobilemenu>
сюда добавить атрибут container чтобы были по умолчанию паддинги левый и правый по 20рх

2021-11-13 21:27 UTC, croixua commented on src/sass/layout/_mobmenu.scss
> +  padding: 40px 0px;
будет перебивать стили контейнера, лучше просто поставить padding-top: 60px;

там по макету 60

2021-11-13 21:27 UTC, croixua commented on src/sass/layout/_mobmenu.scss
> +  transition-property: fill;
это мы пока что не трогаем

2021-11-13 21:27 UTC, croixua commented on src/sass/layout/_mobmenu.scss
> +  @media screen and (min-width: 768px) {
медиа-запросы пока не делаем, все силы бросаем на статическую мобильную версию

2021-11-13 21:27 UTC, croixua commented on src/sass/layout/_mobmenu.scss
> +  transition-property: transform;
анимации пока что убираем

2021-11-14 16:45 UTC, canon318i commented on src/partials/mobmenu.html
> +    <div class="buy-now">
Посчитал число дивов в коде, их всего 4 шт, т.е. пары дивов есть. Валидатор тоже не нашел ошибки.
Див вокруг кнопки - как враппер, чтобы не позиционировать кнопку абсолютно

2021-11-14 16:46 UTC, canon318i commented on src/partials/mobmenu.html
> +<div class="mobile-menu" data-mobilemenu>
не получится, если на мобильном меню делать для контейнера паддинги по 20pz, горизонтальные полосы не будут доходить до краев экрана

2021-11-14 16:47 UTC, canon318i commented on src/sass/layout/_mobmenu.scss
> +  padding: 40px 0px;
40 это верхний паддинг основного враппера, плюс 20 - враппер вокруг кнопки.

2021-11-14 16:49 UTC, canon318i commented on src/sass/layout/_mobmenu.scss
> +  transition-property: fill;
закомментировал анимацию, если мешает

2021-11-14 16:49 UTC, canon318i commented on src/sass/layout/_mobmenu.scss
> +  @media screen and (min-width: 768px) {
закомментировал мобильный запрос

2021-11-14 16:50 UTC, canon318i commented on src/sass/layout/_mobmenu.scss
> +  transition-property: transform;
закомментировал

2021-11-14 21:30 UTC, closed without merging