feature/products
croixua/command-project-goit pull request #2
Opened 2021-11-13 14:54 UTC by marina1412

2021-11-13 17:50 UTC, croixua reviewed
нужны правки

2021-11-13 17:50 UTC, croixua commented on src/images/Ellipse.svg
> +<svg width="6" height="6" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="3" cy="3" r="3" fill="#fff"/></svg>
Декоративный элемент многоточие под заголовком, выполнить псевдоэлементом.

2021-11-13 17:50 UTC, croixua commented on src/partials/products.html
> +</section>>
лишний > в теге </section>>

2021-11-13 17:50 UTC, croixua commented on src/sass/layout/_products.scss
> +.section__title {
изменить название класса на products-title и в него добавить margin-bottom: 144px;
а базовые стили прописать в section-title

2021-11-13 17:50 UTC, croixua commented on src/sass/layout/_products.scss
> +.section__text {
изменить название класса на products-pretitle и в него добавить margin-bottom: 15px;
а базовые стили прописать в section-pretitle

2021-11-13 17:50 UTC, croixua commented on src/sass/layout/_products.scss
> +}
padding-left 40px
padding-right 40px

2021-11-13 17:50 UTC, croixua commented on src/partials/products.html
> +            <li class="products__item">
если делать по БЭМ, то лучше список назвать products-list и дальше уже отталкиваться от названия этого блока

2021-11-13 17:50 UTC, croixua commented on src/partials/products.html
> +        <p class="section__text">100% natural</p>
добавить два класса products-pretitle и section-pretitle

2021-11-13 17:50 UTC, croixua commented on src/partials/products.html
> +        <h2 class="section__title">products</h2>
добавить два класса products-title и section-title

2021-11-13 17:50 UTC, croixua commented on src/images/Ellipse.svg
> +<svg width="6" height="6" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="3" cy="3" r="3" fill="#fff"/></svg>
уже увидел что выполнено псевдоэлементом, но так в svg я не вижу расстояние между этими точками, там по 4рх?

2021-11-13 17:50 UTC, croixua commented on src/sass/layout/_products.scss
> +    background-repeat: repeat-x;
background-repeat: repeat-x; в тулзах это значение перечеркнуто.
для чего оно?

2021-11-13 17:50 UTC, croixua commented on src/sass/layout/_products.scss
> +.products__title {
добавить margin-bottom: 30px, а у :after удалить margin-bottom

2021-11-13 17:50 UTC, croixua commented on src/sass/layout/_products.scss
> +.products__title {
допустим дизайнер решил убрать многоточие и чтобы в итоге у нас ничего не поломалось

2021-11-13 17:50 UTC, croixua commented on src/sass/layout/_products.scss
> +    width: 23px;
ширина должна быть 26рх и расстояние между точками 4рх

В общем, я бы лучше делал не через svg, а через верстку эти точки

2021-11-13 17:50 UTC, croixua commented on src/sass/layout/_products.scss
> +    width: 23px;
height 6px
width 6px
background-color #fff
border-radius 50%

это как информация к размышлению, а там надо подумать

2021-11-13 17:50 UTC, croixua commented on src/sass/layout/_products.scss
> +  @include font(400, 14px, 21px, 0.04em);
тут не 400, а 700

2021-11-14 12:20 UTC, marina1412 commented on src/partials/products.html
> +</section>>
исправлено

2021-11-14 12:30 UTC, marina1412 commented on src/sass/layout/_products.scss
> +.section__title {
исправлено

2021-11-14 12:39 UTC, marina1412 commented on src/sass/layout/_products.scss
> +.section__title {
класс назвала section__title--margin

2021-11-14 12:41 UTC, marina1412 commented on src/sass/layout/_products.scss
> +.section__text {
Исправлено. Класс назвала section__pretitle--margin

2021-11-14 12:43 UTC, marina1412 commented on src/sass/layout/_products.scss
> +}
Исправлено

2021-11-14 12:43 UTC, marina1412 commented on src/partials/products.html
> +        <h2 class="section__title">products</h2>
Исправлено

2021-11-14 12:44 UTC, marina1412 commented on src/sass/layout/_products.scss
> +    background-repeat: repeat-x;
Исправлено

2021-11-14 12:45 UTC, marina1412 commented on src/sass/layout/_products.scss
> +  @include font(400, 14px, 21px, 0.04em);
Исправлено

2021-11-14 13:22 UTC, marina1412 commented on src/sass/layout/_products.scss
> +    width: 23px;
исправлено

2021-11-14 17:12 UTC, croixua requested changes

2021-11-14 17:12 UTC, croixua commented on src/partials/products.html
> +            <li class="products__item">
нужно переименовать

2021-11-14 17:12 UTC, croixua commented on src/sass/layout/_products.scss
> +.section__title {
нужно было сделать, как написано

2021-11-14 17:12 UTC, croixua commented on src/sass/layout/_products.scss
> +  &::before {
нужно добавить абсолютное пизиционирование и трансформ транслейт

2021-11-14 19:13 UTC, croixua submitted a review, later dismissed

2021-11-14 20:10 UTC, croixua approved these changes

2021-11-14 20:10 UTC, merged